sudo: required
language: node_js
node_js:
  - 7

services:
  - docker

before_install:
  - docker build -t jmbau/docker-rea -f Dockerfile.dev .

script:
  - docker npm test jmbau/docker-rea -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Thistalk"
  env: "Thistalk-env"
  bucket_name: "elasticbeanstalk-us-east-2-975845124120"
  bucket_path: "Thistalk"
  on:
    branch: master
  access_key_id: $AccesskeyID
  secret_access_key:
    secure: "$Secretaccesskey"
    

