sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jmbau -f Dockerfile.dev .

script:
  - docker run -e CI=true jmbau npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frank"
  env: "Frank-env"
  bucket_name: "elasticbeanstalk-us-east-2-975845124120"
  bucket_path: "frank"
  on:
    branch: master
  access_key_id: $AccesskeyID
  secret_access_key: $Secretaccesskey